### ISSUE TITLE
sketch too big?

### ISSUE THREAD

**Issue by Park2009** [taneken/USBKBD2X68K#1]
Hello
I'm going to use it for Arduinopromini.
When attempting to compile, the message "sketch too big" was displayed and the compile was failed.
About 220kb of storage memory space seems to be insufficient.
please help me.
thanks.

I reinstalled the USB host shield library and the problem was solved.

**Comment by taneken** [comment]
I'm sorry for the late reply.
You've solved it.
Older libraries are larger and can cause errors. I was also worried once.
