### ISSUE TITLE
コンパイルエラーが発生しました

### ISSUE THREAD

**Issue by tkdesign-jp** [taneken/USBKBD2X68K#2]
USBKBD2X68K.inoを最新のArduino IDEでコンパイルしたところ、
下記のようなエラーが出ますが何か解決方法はありますか？

最大30720バイトのフラッシュメモリのうち、スケッチが30826バイト（100%）を使っています。
最大2048バイトのRAMのうち、グローバル変数が1327バイト（64%）を使っていて、ローカル変数で721バイト使うことができます。
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board
ボードArduino Pro or Pro Miniに対するコンパイル時にエラーが発生しました。

その後、boards.txtを編集することでunoと同等にコンパイルが出来て解決しました。

**Comment by windship** [comment]
kikuonさん

boards.txtの編集内容に対して教えていただけますか？
同じサイズエラーでコンパイルできない状態です。
